### ISSUE TITLE
What is the red highlighting indicating here?

### ISSUE THREAD

**Issue by stkent** [exercism/xkotlin#46]
Not sure if [this](http://exercism.io/submissions/a8d62ce0aef746b191e6bf841b3cf281) is a syntax highlighting error or indicative of some (whitespace?) issue with my solution:

<img width="581" alt="screen shot 2017-05-26 at 7 08 12 pm" src="https://cloud.githubusercontent.com/assets/6463980/26515240/c7511b8c-4246-11e7-979e-f887e1ebb9cc.png">

Thanks in advance for any clarification you are able to provide 😄

**Comment by kytrinyx** [comment]
@stkent My first thought was that it might be a mix of tabs/spaces coming out in some funky way, but I checked and you don't have weird whitespace. I have no idea what's going on here!

**Comment by stkent** [comment]
Spooky! Thanks for looking into it :)

**Comment by petertseng** [comment]
I have a suspicion (but what do I know? I only looked at this code for 5 minutes and don't actually  understand rouge at all) that https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/kotlin.rb does not know what a companion object is. http://exercism.io/submissions/3c4b6738a2c54c3680d689cb8cef846d also has it. I like to think that I don't have whitespace issues, but I guess it could happen.

**Comment by petertseng** [comment]
Fun fact. The lexer [knows what a `class object` is](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/kotlin.rb#L44), but they [were renamed](https://blog.jetbrains.com/kotlin/2015/03/follw-up-new-class-object-syntax/) to `companion object`, and the lexer was not updated for this fact.

**Comment by kytrinyx** [comment]
@petertseng that's some great detective work!

**Comment by stkent** [comment]
Nice find!

**Comment by stkent** [comment]
Hopefully https://github.com/jneen/rouge/pull/702 fixes this 🤷‍♂️

**Comment by stkent** [comment]
Since the underlying cause of this issue has been identified as belonging to a third-party tool, and a patch has been submitted to that tool, I think there's no more action required here. Closing.
