### ISSUE TITLE
Proposal: update track order and exercise difficulty estimates to match xjava

### ISSUE THREAD

**Issue by stkent** [exercism/xkotlin#49]
Thinking:

0) Kotlin is about to receive a lot more attention now that it's a first-class language on Android; any high-leverage changes that improve the Exercism Kotlin experience are especially important at this moment in time;
1) Recent Java track order changes to incorporate estimated exercise difficulty have resulted in notably lower drop-off during the early exercises; the current order in xkotlin does not account for exercise difficulty;
2) The difficult of exercises is likely to be very similar between the two languages;
3) It's easy to refine order later on (this is an ongoing process in xjava).

**Comment by sdavids13** [comment]
👍
