### ISSUE TITLE
Find additional peer reviewers

### ISSUE THREAD

**Issue by sdavids13** [exercism/xkotlin#7]
It would be great to get more people to get involved with peer reviewing code, by providing suggestions on how to use Kotlin specific features to provide a more readable, understandable solution.

Anyone who is interested, please leave a comment letting us know that you are interested in doing so.

**Comment by bkarlovitz** [comment]
Hi. I'm Bryan. 

I'm interested in helping with this. I have fairly minimal Kotlin experience, but I want to learn. Let me know what I can do :)

**Comment by sdavids13** [comment]
Great to hear! There are a couple of things you could do depending on your comfort level:

1. Add [more modules](http://exercism.io/languages/kotlin/contribute). Basically you just fork this repo, import the "exercises build.gradle" file in IntelliJ and start adding new submodules (you need to update the settings.gradle to include the new module name and refresh the gradle projects for the update to be seen).
    - I can then peer review your code if you are looking to learn ;)
2. Become a track peer reviewer, this really entails:
    - The code reviews do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore aspects of the language. Referencing existing blog posts and style guides seems to work well, when making specific recommendations.
    - I have found the [Kotlin documentation](https://kotlinlang.org/docs/reference/idioms.html) to be pretty top notch and can easily provide anchor urls to specific sections of the documentation which can provide a better result.
3. Update various documentation that you might find lacking (there are some gaps). If you started to do any of the exercises and thought something wasn't clear lets get that taken care of for new people to be able to hit the ground running as quickly as possible.

Let me know which you are willing to help with, and we can go from there. If you do wan to become a track reviewer, we will have @kytrinyx add you so you can view everyone's solutions without having to upload your own.

Thanks for willingness to help!

**Comment by bkarlovitz** [comment]
It sounds like I can get started now on 1 and 3. I'll let you know if I want anything reviewed. 

As for 2, I'd be happy to do that as well. If @kytrinyx wants to add me, I'll get started.

**Comment by kytrinyx** [comment]
I've added you @bkarlovitz. Thanks!

**Comment by cswagner** [comment]
Hello. I'm Chris.

I added the hello-world exercise, but would love to continue helping out on 1, 2, and 3 mentioned by @sdavids13 above.

**Comment by michel-slm** [comment]
Hi @sdavids13 , everyone,

Ah, I proposed the `xkotlin` module a while back but then got sidetracked by $dayjob ... will try and get back up to speed!

**Comment by kytrinyx** [comment]
> create tickets for the ones you are planning on implementing so we don't step on each others toes.

+1 -- or "WIP" pull requests (`git commit --allow-empty -m "WIP: add $module-name"`)

> can you add @cswagner and @michel-slm as track reviewers?

Done! I also just recalled that in your account page you can add more track mentors on tracks where you're a mentor. I'll document that somewhere :)

**Comment by sdavids13** [comment]
Ah, I see it - will do in the future.

**Comment by jtigger** [comment]
Hey @exercism/kotlin, how are we doing on this?

**Comment by sdavids13** [comment]
@jtigger This track isn't super active, interested in lending a hand?

**Comment by jtigger** [comment]
Yes, sir!  Thanks for asking!
