### ISSUE TITLE
Port (some) tests to spock

### ISSUE THREAD

**Issue by geoand** [exercism/xkotlin#8]
Do you think it would be beneficiary to the project to port the tests to Spock?
Maybe if not all (lots of them are pretty trivial and would not gain much from such a port - although the Groovy  power-assert feature is pretty handy), just the ones that use parameterized tests? Those would definitely be a lot more clear using Spock.

I could easily perform the aforementioned port if you guys think it's worth it.

Thanks!

**Comment by sdavids13** [comment]
I would prefer to keep the entire code base written in Kotlin, otherwise having users look at tests written in Groovy can lead to confusion. Maybe something like [kotlin test](https://github.com/kotlintest/kotlintest) or [spek](https://github.com/JetBrains/spek) could lead to more clarity while still remaining in the Kotlin mindset. 

Part of this is also know your users, I believe a lot of the users who will be drawn to Kotlin are Java developers - those users will have the most experience with JUnit. At that point if we leave the tests the way they expect them they can concentrate more on the code than learning how to read new test frameworks, though this is less of an issue if the test framework is more readable/self documenting.

**Comment by geoand** [comment]
Thanks for the prompt reply @sdavids13!

I agree that the bulk of Kotlin users will be coming from the hardcore Java camp. However lately there seems to be a great interest (and perhaps fear) in Kotlin from the Groovy ecosystem as well.
Moreover, Spock is becoming more and more prevalent for testing of all kinds of JVM apps due to it's clarity and BDD style syntax.

Ultimately though, I agree that porting the tests to Spock probably won't provide much added value to the project.
After thinking it through, I also realized that moving the tests to Spock would break a lot of the existing implementations since a lot of the tests would need the presence of @JvmStatic in order to work.

**Comment by sdavids13** [comment]
Are you interested in trying out those other frameworks to see if they would add any more clarity?

Or if perhaps [add more modules](https://github.com/exercism/xkotlin/issues/7#issuecomment-223162476)?

**Comment by geoand** [comment]
I'd be glad to help with both!
I have used Spec before, but I'll check out Kotlin test as well to give more clarity with the tests.

As for adding new modules, which module(s) would you like me to work on?

**Comment by sdavids13** [comment]
Kotlin test is pretty much a clone of Scala test from a functionality perspective.

> As for adding new modules, which module(s) would you like me to work on?

Pick your poison, just call dibs on the modules you want to work on via creating a new ticket or creating an empty pull request. You can see the non-implemented modules [here](http://exercism.io/languages/kotlin/contribute), I've found it useful to snag other language's implementations/tests and migrate it over to Kotlin (I took a lot of the low-hanging fruit of taking the Java tests and using the Scala implementations). For the canonical tests you can see them [here](https://github.com/exercism/x-common) (<module-name>.json) - I was attempting to create a framework to parse the json files and generate unit tests but ran into a few snags and didn't complete it - for the time being I'm just manually porting over the tests.

**Comment by geoand** [comment]
Kotlin test seems interesting and pretty active, but I am hesitant to start using because of the lack of support for parameterized tests (although this [feature](https://github.com/kotlintest/kotlintest/issues/5) seems to be coming soon). So I propose to hold off on the porting of the tests until parameterized tests are supported.

I'll start adding new modules as explained :)
Thanks!
